### PR TITLE
node v18 compatiblity fix

### PR DESCRIPTION
**Pull request by zishon89us**
Hi - This patch fixes the conflicting issue with node v18.

### CODE REVIEW

**Comment by Milad** [comment]
Can you please clarify more about the conflicts? I haven't been using this tool, so I'm not aware of them..

**Comment by zishon89us** [comment]
In a NodeJS app built using v16 package was working fine, but as I switched to NodeJS v18 it started yielding the following (screenshot) error:

image

So the issue seems to be because of NodeJS v18 breaking changes, whilst simply changing the variable from `closed` to `isClosed` fixed it.

**Comment by zishon89us** [comment]
any feedback?

**Comment by Milad** [comment]
Merged and released. Thank you!

**Pull request merged**
